### ISSUE TITLE
Window Manager approach does not account for occluded content

### ISSUE THREAD

**Issue by neatorobito** [microsoft/surface-duo-window-manager-samples#14]
I am working on an app for the Duo and I just finished implementing the window manager approach as used in the TwoDo app. I noticed that in **both the sample TwoDo app and my app** this approach doesn't seem to account for the region occluded by the hinge. The `ReactiveGuide` used for the vertical and horizontal folds has visibility `GONE` and doesn't have a width. In general it behaves very oddly.

## What this means:
If you add a simple view (like a textview) at the hinge adjacent edges of a set of containers, you'll see that one of them is occluded by the hinge.

![image](https://user-images.githubusercontent.com/3013405/129790438-b5806fc9-c42e-4704-8b14-708d39828cf9.png)

Below, the pink container's end is constrained to the start of the vertical fold. The green container's start is constrained to the end of the vertical fold.

![image](https://user-images.githubusercontent.com/3013405/129783020-effa6fb0-3699-4f91-8cc0-05e938bca86e.png)

In the layout inspector, you can see that the pink start container is a little bigger than the green end container from stretching into the hinge area (about 33dp or 82.5 raw pixels at the Surface Duo's dpi).

![image](https://user-images.githubusercontent.com/3013405/129785924-24ce92c8-70bf-45fa-87ff-832b9df4d19a.png)
![image](https://user-images.githubusercontent.com/3013405/129786024-59e04c95-862f-4b02-b425-10fa41f93e99.png)

If you call `ScreenInfo.getHinge().width()`, it returns 84 pixels. This is close enough to the 82.5 raw pixel difference the layout inspector is reporting to not be a coincidence.

## Solution & TLDR

ReactiveGuides don't account for an occluding hinge. I expected that the APIs would handle this (and I suspect many other developers will as well). You can fix it by padding the end of the container with whatever `ScreenInfo.getHinge().width()` returns.

```
        if(duoScreenProviderInfo.isSurfaceDuoDevice())
        {
            // ReactiveGuides specified in the layout (vert_fold and horiz_fold) don't provide full
            // support for devices with occluding folds like the Duo. We need to manually draw
            // the region that is occluded, otherwise our fragments will extend into that space.

            // Check that you're in dual screen mode, etc. then the call below should never fail.
            val hingeRegion = duoScreenProviderInfo.getHinge()!!

            // For a vertical orientation updatePadding(left, top, right, bottom)
            // startContainer.updatePadding(0, 0, hingeRegion.width(), 0)

            // For a horizontal orientation updatePadding(left, top, right, bottom)
            // endContainer.updatePadding(0, hingeRegion.height(), 0, 0)
        }
```

**When vertical update the startContainer, when horizontal update the endContainer.**

I can confirm this works in the emulator and on a real device. I assume this is how the `SurfaceDuoLayout` libraries may be handling this, but I was not able to get them working for my use case. Either way, I'd like to use the device agnostic APIs as much as possible.

![image](https://user-images.githubusercontent.com/3013405/129789572-7e1a552d-5c6c-4031-8cdc-fbe069fbff54.png)

Would you all be willing to update the samples and/or docs with this?

**Comment by conceptdev** [comment]
Hey @neatorobito thanks for the feedback! When I look closely at the TwoDo app, I do see that even the centered text is slightly to the right rather than centered, which would be explained by your discovery about not taking the hinge width into account.

This repo is intended to use only the device-agnostic APIs, so we'd want to avoid using `isSurfaceDuoDevice`. Other than that, if you are interested in sending a PR, please do! I'd recommend just doing the minimal change to TwoDo and we can discuss the resulting code. Otherwise, definitely adding this to our backlog. This issue would get updated with a link to the PR when we get to it.

We'll then have to review the other samples as well, and potentially apply the fix there as well.

**Comment by neatorobito** [comment]
`isSurfaceDuoDevice` can probably be replaced with `Build.MODEL`. The bigger question is with regard to `getHinge().getWidth()`. Is that just a hard coded value under the hood or is there something fancier happening with that API?

**Comment by conceptdev** [comment]
The `isSurfaceDuoDevice` [implementation](https://docs.microsoft.com/dual-screen/android/sample-code/is-dual-screen-device) is preferred over `Build.MODEL` because based on a feature string which is more reliable. `getHinge` is not hardcoded, it is using the [DisplayMask](https://docs.microsoft.com/dual-screen/android/api-reference/display-mask) package to query the system for actual coordinates of the hinge masked area.

Either way, for a solution that works on all foldable and dual-screen devices, the recommendation would be to use Window Manager like all the samples in this repository, and test for the presence of a `FoldingFeature` and use the properties

In the case of TwoDo, I just pushed #18 to use the left boundary of the hinge as the target for the ReactiveGuide, which fixes the text centering at the expense of the notepad image being slightly off-center. Then added padding, as you suggested, so that the image is also correctly centered and the area behind the hinge only obscures the padded area. The padding is calculated using `FoldingFeature.bounds` which is the Window Manager equivalent of `getHinge`.

**Comment by neatorobito** [comment]
Okay, I see those other changes as well. Excellent! This is a holistic solution and it addresses my concerns. I'll close the issue.
